### ISSUE TITLE
When switching servers, players are counted as 2 players.

### ISSUE THREAD

**Issue by TheDeafCreeper** [Aelysium-Group/rusty-connector#33]
When a player is moved from one server to another, the target server's player count will increase by 2 instead of 1. This does not happen on first join.

The issue also corrects itself once the server resyncs.

**Comment by nathan-i-martin** [comment]
Will take a look into this and see if it makes sense to fix. Its known that server count set by the proxy might not be correct (hence why the reruns system exists)
Depending on what is causing the duplicate to occur this may or may not make sense to fix (since it'll ultimately resync anyways)

**Comment by nathan-i-martin** [comment]
I can't seem to find what might be causing this. If someone else is able to find it I'll be happy to go in and take care of it. Because of what I mentioned earlier this isn't something I'm willing to spend much time figuring out so for now I'm going to close this.
