### ISSUE TITLE
Problems with the hub command

### ISSUE THREAD

**Issue by chencu5958** [Aelysium-Group/rusty-connector#49]
After enabling the hub feature, the first time you start the hub command will not take effect, you must use `rc reload` to

**Comment by nathan-i-martin** [comment]
I suspect this might be something related to references not being coupled. Will look into it.

**Comment by nathan-i-martin** [comment]
can you use `// debug` (or `rc debug` they're the same) and send me the output? Also what version is this?

**Comment by chencu5958** [comment]
> can you use `// debug` (or `rc debug` they're the same) and send me the output? Also what version is this?

Using rc reload to look at the debug is the same output

RC Version: 0.7.1
Debug output: https://pastebin.com/MmHcusK1

**Comment by chencu5958** [comment]
The transmission anchors and tpa under the same module as it can register commands and use them normally, but it's not clear why hub can register but just doesn't show up.

**Comment by nathan-i-martin** [comment]
The dynamic teleport module is a lazy when it comes to reporting errors. So there was probably an issue booting it the first time but we just aren't seeing it.

**Comment by chencu5958** [comment]
> The dynamic teleport module is a lazy when it comes to reporting errors. So there was probably an issue booting it the first time but we just aren't seeing it.

That's a possibility, I'll troubleshoot it later, so far I can determine that the first time I boot, the hub command doesn't work, I have to use `rc reload`, and after rebooting the problem recurs again

**Comment by nathan-i-martin** [comment]
That's not suprising. using `// reload` runs the exact same code that the plugin's boot sequence uses

**Comment by nathan-i-martin** [comment]
Considering how well v0.8.0 development has been going, I think I'm gonna move this bug fix to that version.

**Comment by nathan-i-martin** [comment]
Can you describe what specifically happens when you run `/hub`? Does the player get an error message? does anything get sent to the console?

**Comment by chencu5958** [comment]
> Can you describe what specifically happens when you run `/hub`? Does the player get an error message? does anything get sent to the console?

The first time you start using it, it doesn't report an error and doesn't react, but after using rc reload and using the hub command, this error will appear, but after a while it disappears on its own.
https://pastebin.com/twsgXqLF

**Comment by nathan-i-martin** [comment]
Seems to be fixed, I had no issues with this during testing. If this issue persists for you, be sure to configure the `hub.enabled-families` part so that the hub command is enabled in the correct families.
