### ISSUE TITLE
RC using Docker ContainerID as Hostname

### ISSUE THREAD

**Issue by phaefner1** [Aelysium-Group/rusty-connector#58]
Hi, I have a Problem with my Setup:

Setup:
2 VPS, on VPS1 (master) the RC / Velocity Proxy is running.
On VPS2 (worker1) i have a MC Server in Docker, also running RC as Client.

The dockerized server on worker1 is able to connect  to the proxy using its container ip address. 
Since the 2 VPS share the Network, they can reach (ping, telnet) each other.

![rc2](https://github.com/Aelysium-Group/rusty-connector/assets/89690507/b9d2c7d5-d7ad-4119-8720-82d28cdcaf45)

In the "address" field in the client config i put the correct ip address, but RC resolves this IP to the docker container id and registers the Server as <containerid>:25565 on the proxy, making it impossible to connect to it.

![rc3](https://github.com/Aelysium-Group/rusty-connector/assets/89690507/6933364d-eb14-4c40-9d03-46d3325d2f23)

![rc1](https://github.com/Aelysium-Group/rusty-connector/assets/89690507/d4ab7c52-e412-46e7-9c70-fc2649393dc5)

This is also reproducable if u just have 1 VPS with a proxy and a mc server running in docker that connects to the proxy. Screenshots attached.

If i add the docker containerid to my /etc/hosts file and make it resolve to the ip again, everything works fine. But thats just a silly workaround and not what i want, since i want my setup to be flexible and scale.

**Comment by nathan-i-martin** [comment]
I've been reviewing the code for Velocity. It looks like AddressUtil.parseAddress is used to parse the address used by the server registration, where in RC we're using parseAndResolve. I'm going to be changing this so hopefully that should fix this issue.

**Comment by nathan-i-martin** [comment]
Potential fix has been made in branch `v0.7.2`. I don't have a docker setup, if someone could test it can get back to me on that, that'd be awesome.
CC @phaefner1
