### ISSUE TITLE
Unable to import toolkit in Gradle

### ISSUE THREAD

**Issue by ajh123** [Aelysium-Group/rusty-connector#73]
I'm trying to import the toolkit with Gradle, but it cannot find the toolkit in the repository

```
:BedWars:main: Could not find group.aelysium:rustyconnector-toolkit:0.8.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://repo.screamingsandals.org/public/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://oss.sonatype.org/content/repositories/snapshots/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://repo.papermc.io/repository/maven-public/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://hub.spigotmc.org/nexus/content/repositories/snapshots/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - file:/C:/Users/samro/.m2/repository/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://repo.onarandombox.com/content/groups/public/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://repo.codemc.org/repository/maven-public/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
  - https://repo.alessiodp.com/releases/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom
Required by:
    project :BedWars > project :BedWars-common
```

When I navigate to `https://repo.codemc.org/repository/maven-public/group/aelysium/rustyconnector-toolkit/0.8.0/rustyconnector-toolkit-0.8.0.pom` in a browser it does a 404.

Also when I search for rustyconnector-toolkit in the repository viewer the toolkit isn't found either.

![image](https://github.com/Aelysium-Group/rusty-connector/assets/41990982/becc5f88-dd6f-47d0-a673-5b8a48cfdf5d)

*This issue doesn't use any of the provide templates since its not a plugin bug or a compatibility issue*

**Comment by ajh123** [comment]
In the mean time I'm going to make my plugin execute the `/rc send ...` command I need.

**Comment by nathan-i-martin** [comment]
This is PEBKAC.
Look over:
https://wiki.aelysium.group/rusty-connector/toolkit/installation

If you need further assistance you can join the discord and get support there: https://join.aelysium.group/

**Comment by ajh123** [comment]
I have already looked at the wiki, and I have created a new empty Gradle project and still have the same issue.

https://github.com/miners-online/network-utils/blob/main/velocity/build.gradle

I can't use your discord since it requires a phone number.

**Comment by nathan-i-martin** [comment]
Thank you for providing a build gradle.
Looks like I made a typo on the website or something. You wanna use `/releases` instead of `/snapshot`.

Apologies for the swift closing. With the information provided in the initial post, it seemed as tho you simply didn't define the MrNavaStar repo as there was no mention of it anywhere. Regardless I'll get that sorted out!

**Comment by ajh123** [comment]
@nathan-i-martin 

Thanks, that worked. I also had to add the repository to the [parent project](https://github.com/miners-online/network-utils/blob/main/build.gradle) Gradle script too - _should this be noted on the docs too?_

**Comment by nathan-i-martin** [comment]
No I don't think so.
All the docs cares about is telling you how to add the repo + api to your project.
If a user has a more complicated project structure, that's a gradle thing, not RC
