### ISSUE TITLE
Server stalls on shutdown.

### ISSUE THREAD

**Issue by TheDeafCreeper** [Aelysium-Group/rusty-connector#9]
When shutting down the server, the following warning pops up and stalls shutdown.

```
[21:27:19 INFO]: [rustyconnector-paper] Disabling rustyconnector-paper v0.5.1
[21:27:19 WARN]: [io.lettuce.core.RedisChannelHandler] Connection is already closed
```

The server never seems to finish shutdown.

**Comment by nathan-i-martin** [comment]
The `#shutdown()` method used in Lettuce seems to have a known problem with causing stalls. Once we sort out #11 I'll work on this.

**Comment by nathan-i-martin** [comment]
In local tests, while I have seen this warning message anytime I shutdown, it has not caused a stall for me at all.
On Velocity, when trying to close without any plugins, it will always ask me if I wanna terminate a batch process (y/n) which requires input. But that isn't a result of the plugin or warning. On paper, the shutdown process is not stalled at all.

It's possible that the stall you are experiencing is a result of another plugin. Try a binary search and let me know the results

**Comment by TheDeafCreeper** [comment]
I have not had any server stalls recently even without changing anything which is odd, I think I'll close this for now and if it pops back up again I'll create a new issue if I can't find any other cause.
